name: cpegen
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - asttokens=2.4.1
  - attrs=23.2.0
  - aws-c-auth=0.7.16
  - aws-c-cal=0.6.10
  - aws-c-common=0.9.14
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.6
  - aws-c-mqtt=0.10.3
  - aws-c-s3=0.5.3
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.4
  - aws-sdk-cpp=1.11.267
  - blas=2.121
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - cuda-cccl=12.4.99
  - cuda-cccl-impl=2.0.1
  - cuda-cccl_win-64=12.4.99
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.99
  - cuda-opencl-dev=12.4.99
  - cuda-profiler-api=12.4.99
  - cuda-runtime=12.1.0
  - cuda-version=12.4
  - datasets=2.18.0
  - debugpy=1.8.1
  - decorator=5.1.1
  - dill=0.3.8
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.13.3
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2024.2.0
  - huggingface_hub=0.22.1
  - idna=3.6
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - intel-openmp=2024.0.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - ipywidgets=8.1.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.10
  - khronos-opencl-icd-loader=2023.04.17
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.1
  - libarrow=15.0.2
  - libarrow-acero=15.0.2
  - libarrow-dataset=15.0.2
  - libarrow-flight=15.0.2
  - libarrow-flight-sql=15.0.2
  - libarrow-gandiva=15.0.2
  - libarrow-substrait=15.0.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.5.119
  - libcurand-dev=10.3.5.119
  - libcurl=8.6.0
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.20
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgoogle-cloud=2.22.0
  - libgoogle-cloud-storage=2.22.0
  - libgrpc=1.62.1
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libparquet=15.0.2
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.6
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.6
  - mkl=2024.0.0
  - mkl-devel=2024.0.0
  - mkl-include=2024.0.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - multidict=6.0.5
  - multiprocess=0.70.16
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.2.1
  - orc=2.0.0
  - packaging=24.0
  - pandas=2.2.1
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=24.0
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pyarrow=15.0.2
  - pyarrow-hotfix=0.6
  - pygments=2.17.2
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.11
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywin32=306
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - re2=2023.09.01
  - regex=2023.12.25
  - requests=2.31.0
  - safetensors=0.4.2
  - setuptools=69.2.0
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.45.2
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.11.0
  - tk=8.6.13
  - tokenizers=0.15.2
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.2
  - transformers=4.39.1
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - urllib3=2.2.1
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.13
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - accelerate==0.28.0
      - astunparse==1.6.3
      - flatbuffers==24.3.25
      - gast==0.5.4
      - google-pasta==0.2.0
      - grpcio==1.62.1
      - h5py==3.10.0
      - keras==3.1.1
      - libclang==18.1.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - namex==0.0.7
      - opt-einsum==3.3.0
      - optree==0.11.0
      - protobuf==4.25.3
      - rich==13.7.1
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.1
      - tensorflow-intel==2.16.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - torchaudio==2.2.1
      - torchvision==0.17.1
      - werkzeug==3.0.1
      - wrapt==1.16.0
